export const SET_MUSIC = 'SET_MUSIC';
export const GET_MUSIC_REQUESTED = 'GET_MUSIC_REQUESTED';
export const GET_MUSIC_SUCCESS = 'GET_MUSIC_SUCCESS';
export const GET_MUSIC_FAILED= 'GET_MUSIC_FAILED';