export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export const GET_MUSIC_REQUESTED = 'GET_MUSIC_REQUESTED';
export const GET_MUSIC_SUCCESS = 'GET_MUSIC_SUCCESS';
export const GET_MUSIC_FAILED= 'GET_MUSIC_FAILED';